networks:
  itu-minitwit-network:
    external: false
    name: itu-minitwit-network

services:
  frontend:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    image: minitwit/webapp
    ports: 
      - "80:5000"
    networks:
      - itu-minitwit-network
    depends_on:
      db:
        condition: service_healthy
      grafana:
        condition: service_started
      prometheus:
        condition: service_started
    environment:
      db_IP: db
      db_password: knowledge
      db_name: minitwit_db


  db: 
    build: 
      dockerfile: docker/db/Dockerfile 
    image: minitwit/db 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: knowledge
      POSTGRES_DB: minitwit_db
    networks:
      - itu-minitwit-network
    depends_on:
      grafana:
        condition: service_started
      prometheus:
        condition: service_started

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - itu-minitwit-network


  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - itu-minitwit-network

volumes:
  grafana-storage:

