services:
  frontend:
    build: 
      context: .
      dockerfile: docker/Dockerfile_app
    image: minitwit/webapp
    ports: 
      - "80:5000"
    volumes:
      - .:/app
  database:
    build:
      dockerfile: docker/Dockerfile_database
    image: minitwit/database
    ports:
      - "5432:5432"
