name: Dawnscanner

on:
  push:
    branches:
      - ruboCop

jobs:
  dawnscanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Download and Set Up Knowledge Base
        run: |
          echo "Downloading DawnScanner Knowledge Base..."
          curl -LO https://github.com/thesp0nge/dawnscanner_knowledge_base/releases/download/v20240116/kb.tar.gz
          tar -xzf kb.tar.gz
          mkdir -p /home/runner/.dawnscanner/kb
          mv kb.yaml kb.yaml.sig /home/runner/.dawnscanner/kb/
          
          echo "Verifying Knowledge Base..."
          ls -l /home/runner/.dawnscanner/kb/

      - name: Install Dependencies
        run: |
          bundle install
          ls -l Gemfile.lock  # Verify that Gemfile.lock exists after install

      - name: Run DawnScanner
        run: |
          export DAWN_KB=/home/runner/.dawnscanner/kb
          ls -l
          echo "Running DawnScanner..."
          dawn scan .
