name: Dawnscanner
on:
  push:
    branches:
      - ruboCop

jobs:
  dawnscanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Dependencies
        run: bundle install

      - name: Install Knowledge base and Run
        run: |
          ls -l
          curl -LO https://github.com/thesp0nge/dawnscanner_knowledge_base/releases/download/v20240116/kb.tar.gz
          tar -xzf kb.tar.gz
          mkdir -p /home/runner/.dawnscanner/kb  # Create the folder for the knowledge base
          mv kb.yaml kb.yaml.sig /home/runner/.dawnscanner/kb/  # Move only relevant files
          ls -l
          echo "1. -----------------------------------"
          # Set the knowledge base path
          # export DAWN_KB=/home/runner/.dawnscanner/kb
          
          # Verify contents
          ls -l /home/runner/.dawnscanner/kb/
          
          echo "2. -----------------------------------"
          
      
          ls -l 
          

      - name: Run Dawnscanner
        run: |
          # Change to project directory
          cd /home/runner/work/minitwit/minitwit
          ls -l
          echo "3. -----------------------------------"
          dawn scan .
