name: Dawnscanner

on:
  push:
    branches:
      - ruboCop

jobs:
  dawnscanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Dependencies
        run: bundle install

      - name: Run Dawnscanner
        run: dawn scan .
