name: Dawnscanner

on:
  push:
    branches:
      - ruboCop

jobs:
  dawnscanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Dependencies
        run: bundle install

      - name: Install Dawnscanner
        run: |
          gem install dawnscanner

      - name: Set Up Dawnscanner Knowledge Base
        run: |
          mkdir -p ~/.dawnscanner
          curl -L -o dawnscanner_kb.tar.gz https://github.com/thesp0nge/dawnscanner-knowledge-base/tarball/main
          tar -xzf dawnscanner_kb.tar.gz
          mv thesp0nge-dawnscanner-knowledge-base-* ~/.dawnscanner/kb

      - name: Run Dawnscanner
        run: dawn scan .
