name: Dawnscanner

on:
  push:
    branches:
      - ruboCop

jobs:
  dawnscanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Dawnscanner
        run: |
          gem install dawnscanner --user-install
          echo "$HOME/.local/share/gem/ruby/3.2.0/bin" >> $GITHUB_PATH

      - name: Verify Dawnscanner Installation
        run: gem list | grep dawnscanner

      - name: Run Dawnscanner
        run: |
          dawnscanner scan --knowledge-base ./dawnscanner_kb --output dawnscanner_report.txt
        continue-on-error: true

      - name: Upload Dawnscanner Report
        uses: actions/upload-artifact@v4
        with:
          name: dawnscanner-report
          path: dawnscanner_report.txt