name: Dawnscanner
on:
  push:
    branches:
      - ruboCop

jobs:
  dawnscanner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Dependencies
        run: bundle install

      - name: Install Knowledge base and Run
        run: |
          curl -LO https://github.com/thesp0nge/dawnscanner_knowledge_base/releases/download/v20240116/kb.tar.gz
          tar -xzf kb.tar.gz  
          mkdir -p /home/runner/.dawnscanner/kb  # Create the folder for the knowledge base
          mv * /home/runner/.dawnscanner/kb/  # Move all extracted contents (check if kb.yaml is included)
          
          # Verify the contents of the knowledge base
          ls -l /home/runner/.dawnscanner/kb/
          
          # Move to the parent directory (where Gemfile.lock is)
          cd ..
          
          # Verify that Gemfile.lock is present
          pwd
          ls -la
          
          # Run dawn scan from the parent directory
          dawn scan .
