name: linting.yml

on:
  pull_request:
  push:
    branches:
      - ConvertToRuby

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Dependencies
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop -A --autocorrect-all --out rubocop_report.txt

      - name: Show RuboCop Report
        run: cat rubocop_report.txt

      - name: Upload RuboCop Report
        uses: actions/upload-artifact@v2
        with:
          name: rubocop-report
          path: rubocop_report.txt
