name: Testing

on:
  push:
    branches:
      - Testing-workflow

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.8'  # Adjust the Python version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  
          pip install requests  
          pip install flask 

      - name: Run tests with pytest
        run: |
          pytest refactored_minitwit_tests.py


