name: Testing

on:
  push:
    branches:
      - Testing-workflow

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      # Step 3: Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          DOCKER_COMPOSE_VERSION="1.29.2"  # You can adjust this to your preferred version
          curl -L https://github.com/docker/compose/releases/download/v$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify Docker Compose installation

      # Step 4: Build and start services with Docker Compose
      - name: Build and start services with Docker Compose
        run: |
          docker-compose up -d  # Start services in detached mode

      # Step 5: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install requests
          pip install flask

      # Step 6: Run tests with pytest
      - name: Run tests with pytest
        run: |
          pytest refactored_minitwit_tests.py
        env:
          FRONTEND_URL: "http://localhost:5001"  # URL of your Sinatra app running in Docker
          RACK_ENV: test  # Set environment variable for Sinatra app if needed

      # Step 7: Stop and remove Docker containers
      - name: Stop and remove Docker containers
        run: |
          docker-compose down
