name: Auto Versioning

on:
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest Tag and Increment
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$latest_tag" ]]; then
            new_version="v1.0.0"
          else
            # Increment the patch version (or change the logic to your preference)
            new_version=$(echo $latest_tag | awk -F. '{print $1"."$2"."$3+1}')
          fi
          
          # Optionally add branch name to version if not on main
          branch_name="${GITHUB_REF##*/}"
          if [[ "$branch_name" != "main" ]]; then
            new_version="${new_version}-${branch_name}"
          fi

          echo "New Version: $new_version"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Tag the new version
        run: |
          git tag $NEW_VERSION
          # Delete the remote tag if it exists (ignore error if not found)
          git push origin :$NEW_VERSION || true
          # Push the new tag
          git push origin $NEW_VERSION

      - name: Fetch tags to ensure the new tag is recognized
        run: git fetch --tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.NEW_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  trigger_auto_versioning:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - name: Trigger rpsec test
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/Testing.yml/dispatches\
            -d '{"ref": "main"}'
