name: Auto Versioning

on:
  push:
    branches:
      - version-workflow  # Trigger only on this branch

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Get Latest Tag and Increment
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$latest_tag" ]]; then
            new_version="v1.0.0"
          else
            new_version=$(echo $latest_tag | awk -F. '{print $1"."$2"."$3+1}')
          fi
          
          # Add branch name to version (optional)
          branch_name="${GITHUB_REF##*/}"  # Extract the branch name
          if [[ "$branch_name" != "main" ]]; then
            new_version="${new_version}-${branch_name}"
          fi
          
          echo "New Version: $new_version"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Push New Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's automatic token
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag $NEW_VERSION

          # Use the GitHub token for authentication
          git push https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }}.git $NEW_VERSION
      
