name: Auto Versioning

on:
  push:
    branches:
      - version-workflow  # Trigger only on this branch

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Latest Tag and Increment
        run: |
          latest_tag=$(git tag --sort=-v:refname | head -n 1)
          if [[ -z "$latest_tag" ]]; then
            new_version="v1.0.0"
          else
            # Increment the patch version (or change the logic to your preference)
            new_version=$(echo $latest_tag | awk -F. '{print $1"."$2"."$3+1}')
          fi
          
          # Add branch name to version (optional)
          branch_name="${GITHUB_REF##*/}"
          if [[ "$branch_name" != "main" ]]; then
            new_version="${new_version}-${branch_name}"
          fi

          echo "New Version: $new_version"
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Tag the new version
        run: |
          git tag $NEW_VERSION
          git push origin $NEW_VERSION  # Push the tag to GitHub

      - name: Fetch tags to ensure the new tag is recognized
        run: |
          git fetch --tags  # Make sure the tag is fetched before creating the release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
